# DATABASE SETTINGS
PATH_DB = '/tmp/pokemon_test.db'

# SQLAlCHEMY

DEBUG = True
PORT = 5000
HOST = "127.0.0.1"
SQLALCHEMY_TRACK_MODIFICATIONS = True
SECRET_KEY = "key123"

SQLALCHEMY_DATABASE_URI = f"sqlite:///{PATH_DB}"
